// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKe4mshw7ydg2R64nejNfp6HE7qJF_Mb0',
    appId: '1:248550686469:web:fc9698b129447767bb016c',
    messagingSenderId: '248550686469',
    projectId: 'ecommerce-d826a',
    authDomain: 'ecommerce-d826a.firebaseapp.com',
    storageBucket: 'ecommerce-d826a.appspot.com',
    measurementId: 'G-RTDMZWJ7PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdXZBYT-g2fnC7GvGrqtDM6krmKdMxtI',
    appId: '1:248550686469:android:4e177b036d30b653bb016c',
    messagingSenderId: '248550686469',
    projectId: 'ecommerce-d826a',
    storageBucket: 'ecommerce-d826a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaio_3Ax2OUfSdJyKdwUKnUV0tNuYnQK0',
    appId: '1:248550686469:ios:0d96465bea5ce5babb016c',
    messagingSenderId: '248550686469',
    projectId: 'ecommerce-d826a',
    storageBucket: 'ecommerce-d826a.appspot.com',
    iosBundleId: 'com.example.stylisEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaio_3Ax2OUfSdJyKdwUKnUV0tNuYnQK0',
    appId: '1:248550686469:ios:0d96465bea5ce5babb016c',
    messagingSenderId: '248550686469',
    projectId: 'ecommerce-d826a',
    storageBucket: 'ecommerce-d826a.appspot.com',
    iosBundleId: 'com.example.stylisEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKe4mshw7ydg2R64nejNfp6HE7qJF_Mb0',
    appId: '1:248550686469:web:c81ede962c4ea602bb016c',
    messagingSenderId: '248550686469',
    projectId: 'ecommerce-d826a',
    authDomain: 'ecommerce-d826a.firebaseapp.com',
    storageBucket: 'ecommerce-d826a.appspot.com',
    measurementId: 'G-KXCYF5RZFS',
  );
}
